name: Unit tests of Language translation

on: [push]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd javaCarAPI
          mvn install -DskipTests
          cd ..
          cd CarPath
          mvn clean install
          cd ..
          cd languageprocessing
          mvn -B package --file pom.xml